[build]
  publish = "web"
  functions = "netlify/functions"

[[redirects]]
  from = "/dashboard"
  to = "/dashboard/"
  status = 301

[[redirects]]
  from = "/clients"
  to = "/clients/"
  status = 301

[[redirects]]
  from = "/clients/record"
  to = "/clients/record/"
  status = 301

[[redirects]]
  from = "/leads"
  to = "/leads/"
  status = 301

[[redirects]]
  from = "/tasks"
  to = "/tasks/"
  status = 301

[[redirects]]
  from = "/batch"
  to = "/batch/"
  status = 301

[[redirects]]
  from = "/temp-batch"
  to = "/temp-batch/"
  status = 301

[[redirects]]
  from = "/glp1/ready-to-assign"
  to = "/glp1/ready-to-assign/"
  status = 301

[[redirects]]
  from = "/glp1/assigned"
  to = "/glp1/assigned/"
  status = 301

[[redirects]]
  from = "/glp1/report"
  to = "/glp1/report/"
  status = 301

[[redirects]]
  from = "/glp1/record"
  to = "/glp1/record/"
  status = 301

[[redirects]]
  from = "/settings/user-management"
  to = "/settings/user-management/"
  status = 301

[[redirects]]
  from = "/marketing/schedulers"
  to = "/marketing/schedulers/"
  status = 301

[[redirects]]
  from = "/book"
  to = "/book/"
  status = 301

[[redirects]]
  from = "/companies"
  to = "/companies/"
  status = 301

[[redirects]]
  from = "/brokers"
  to = "/brokers/"
  status = 301

[[redirects]]
  from = "/call-center/in-progress"
  to = "/call-center/in-progress/"
  status = 301

[[redirects]]
  from = "/call-center/other"
  to = "/call-center/other/"
  status = 301

[[redirects]]
  from = "/invoices/dashboard"
  to = "/invoices/dashboard/"
  status = 301

[[redirects]]
  from = "/invoices/data"
  to = "/invoices/data/"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
